
import React from 'react';
import { DashboardLayout } from '@/components/layout/DashboardLayout';
import { CheckCircle2, Circle, Clock, Filter, ListTodo, Plus } from 'lucide-react';
import { mockActionItems } from '@/lib/mock-data';
import { cn } from '@/lib/utils';

export default function ActionCenterPage() {
  return (
    <DashboardLayout>
      <div className="space-y-8">
        <div className="flex items-center justify-between">
          <div>
            <h1 className="text-2xl font-bold text-white">Action Center</h1>
            <p className="text-slate-400">Manage tasks generated by the Intelligence Engine.</p>
          </div>
          <button className="flex items-center space-x-2 px-4 py-2 bg-blue-600 hover:bg-blue-500 text-white text-sm font-semibold rounded-lg shadow-lg shadow-blue-600/20 transition-all">
            <Plus className="h-4 w-4" />
            <span>New Action</span>
          </button>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
          <div className="bg-slate-900/50 border border-slate-800 p-4 rounded-xl">
            <p className="text-sm text-slate-400 font-medium uppercase tracking-wider mb-1">Total</p>
            <p className="text-2xl font-bold text-white">{mockActionItems.length}</p>
          </div>
          <div className="bg-slate-900/50 border border-red-500/20 p-4 rounded-xl">
            <p className="text-sm text-slate-400 font-medium uppercase tracking-wider mb-1">High Priority</p>
            <p className="text-2xl font-bold text-white">{mockActionItems.filter(a => a.priority === 'high').length}</p>
          </div>
          <div className="bg-slate-900/50 border border-slate-800 p-4 rounded-xl">
            <p className="text-sm text-slate-400 font-medium uppercase tracking-wider mb-1">Completed Today</p>
            <p className="text-2xl font-bold text-white">4</p>
          </div>
          <div className="bg-slate-900/50 border border-slate-800 p-4 rounded-xl">
            <p className="text-sm text-slate-400 font-medium uppercase tracking-wider mb-1">Due Today</p>
            <p className="text-2xl font-bold text-white">2</p>
          </div>
        </div>

        <div className="bg-slate-900/50 border border-slate-800 rounded-xl overflow-hidden">
          <div className="p-4 border-b border-slate-800 flex items-center justify-between">
            <div className="flex items-center space-x-4">
              <div className="flex items-center space-x-2">
                <Filter className="h-4 w-4 text-slate-400" />
                <span className="text-sm font-medium text-slate-300">Active Tasks</span>
              </div>
            </div>
            <div className="flex space-x-2">
              <button className="px-3 py-1 text-xs font-medium bg-slate-800 text-white rounded-md border border-slate-700 hover:bg-slate-700 transition-colors">
                Pending
              </button>
              <button className="px-3 py-1 text-xs font-medium text-slate-500 rounded-md hover:bg-slate-800/50 transition-colors">
                Completed
              </button>
            </div>
          </div>

          <div className="divide-y divide-slate-800/50">
            {mockActionItems.map((item) => (
              <div key={item.id} className="p-5 hover:bg-slate-800/20 transition-colors group">
                <div className="flex items-start space-x-4">
                  <button className="mt-1 text-slate-600 hover:text-blue-500 transition-colors">
                    <Circle className="h-5 w-5" />
                  </button>
                  <div className="flex-1">
                    <div className="flex items-center space-x-2 mb-1">
                      <span className={cn(
                        "text-[10px] font-bold uppercase tracking-wider px-1.5 py-0.5 rounded",
                        item.priority === 'high' ? "bg-red-500/10 text-red-400 border border-red-500/20" : 
                        item.priority === 'medium' ? "bg-amber-500/10 text-amber-400 border border-amber-500/20" : 
                        "bg-blue-500/10 text-blue-400 border border-blue-500/20"
                      )}>
                        {item.priority} priority
                      </span>
                      <span className="text-xs text-slate-500">•</span>
                      <div className="flex items-center text-xs text-slate-400 space-x-1">
                        <Clock className="h-3 w-3" />
                        <span>Due {item.dueDate}</span>
                      </div>
                    </div>
                    <h3 className="text-base font-semibold text-white mb-1 group-hover:text-blue-400 transition-colors">{item.title}</h3>
                    <p className="text-sm text-slate-400">{item.description}</p>
                  </div>
                  <div className="flex space-x-2 opacity-0 group-hover:opacity-100 transition-opacity">
                    <button className="p-2 text-slate-500 hover:text-white hover:bg-slate-800 rounded-lg transition-colors">
                      <CheckCircle2 className="h-4 w-4" />
                    </button>
                  </div>
                </div>
              </div>
            ))}
          </div>
        </div>
      </div>
    </DashboardLayout>
  );
}
